### ISSUE TITLE
sh: 1: nodemon: not found during initial run

### ISSUE THREAD

**Issue by blargfoot** [romaannaeem/mern-boilerplate#1]
I received the following error during the initial run on an out of box Ubuntu 18.04 installation.
sh: 1: nodemon: not found

Installing nodemon through the following command resolved the issue:
npm install nodemon --save-dev

You may want to add that to your package.json file.

**Comment by romaannaeem** [comment]
Thanks! I'll fix this ASAP.

**Comment by romaannaeem** [comment]
Fixed.
